"use client";
import Link from "next/link";
import {useState} from "react";
import {agency,products} from "./data";

export function Icon({name}:{name:string}){const p:Record<string,React.ReactNode>={car:<><path d="M5 17h14l-1.5-6h-11L5 17Z"/><path d="M7 11l1.5-4h7L17 11M7 17v2m10-2v2M3 14h2m14 0h2"/></>,home:<><path d="m3 11 9-7 9 7"/><path d="M5 10v10h14V10M9 20v-6h6v6"/></>,heart:<path d="M20.8 5.8c-2.1-2.2-5.6-2.2-7.7 0L12 7l-1.1-1.2a5.4 5.4 0 0 0-7.7 7.5L12 22l8.8-8.7a5.4 5.4 0 0 0 0-7.5Z"/>,briefcase:<><rect x="3" y="7" width="18" height="13" rx="2"/><path d="M8 7V4h8v3M3 12h18M10 12v2h4v-2"/></>,health:<><path d="M12 2 20 5v6c0 5-3.5 9-8 11-4.5-2-8-6-8-11V5l8-3Z"/><path d="M12 7v8m-4-4h8"/></>,person:<><circle cx="12" cy="8" r="4"/><path d="M4 22c.5-5 3-7 8-7s7.5 2 8 7"/></>,bolt:<path d="m13 2-8 12h7l-1 8 8-12h-7l1-8Z"/>,pin:<><path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2"/></>,check:<path d="m5 12 4 4L19 6"/>,layers:<><rect x="3" y="4" width="18" height="6" rx="2"/><rect x="3" y="14" width="18" height="6" rx="2"/></>};return <svg viewBox="0 0 24 24" aria-hidden="true">{p[name]}</svg>}
export function Header(){const[open,setOpen]=useState(false);return <><div className="top"><div className="shell">Insurance guidance for Texas families & businesses <span><a href={`tel:+1${agency.phone1.replaceAll("-","")}`}>{agency.phone1}</a><i/> <a href={`mailto:${agency.email}`}>Email us</a></span></div></div><header><div className="shell nav"><Link href="/" className="logo" aria-label="Semeco Agency home"><b>S</b><span>SEMECO<small>AGENCY LLC</small></span></Link><button className="menu" onClick={()=>setOpen(!open)} aria-expanded={open}>{open?"Close":"Menu"}</button><nav className={open?"open":""}><Link href="/">Home</Link><div className="drop"><button>Insurance <span>⌄</span></button><div>{products.map(p=><Link href={`/${p.slug}`} key={p.slug}>{p.title}</Link>)}</div></div><Link href="/about">About</Link><Link href="/contact">Contact</Link><Link href="/#quote" className="nav-cta">Get a Quote</Link></nav></div></header></>}
export function QuoteForm({title="Let’s find your coverage."}:{title?:string}){return <form className="quote-form" name="quote-request" method="POST" data-netlify="true" action="/thank-you"><input type="hidden" name="form-name" value="quote-request"/><div className="form-title"><span>Free quote request</span><h2>{title}</h2><p>No pressure. Just a helpful conversation.</p></div><label>Full name<input name="full-name" autoComplete="name" required placeholder="Your name"/></label><div className="two"><label>Phone<input type="tel" name="phone" autoComplete="tel" required placeholder="(000) 000-0000"/></label><label>Email<input type="email" name="email" autoComplete="email" required placeholder="you@email.com"/></label></div><div className="two"><label>ZIP code<input name="zip" inputMode="numeric" autoComplete="postal-code" required placeholder="75058" pattern="[0-9]{5}"/></label><label>Insurance type<select name="insurance-type" required defaultValue=""><option value="" disabled>Select one</option>{products.map(p=><option key={p.slug}>{p.title}</option>)}</select></label></div><fieldset><legend>Preferred contact method</legend><label><input type="radio" name="contact-method" value="Phone" defaultChecked/> Phone</label><label><input type="radio" name="contact-method" value="Email"/> Email</label><label><input type="radio" name="contact-method" value="Text"/> Text</label></fieldset><label>How can we help? <span className="optional">Optional</span><textarea name="message" rows={3} placeholder="Tell us what you’d like to protect."/></label><button className="button primary" type="submit">Request my free quote <b>→</b></button><small>Submitting does not bind coverage. We’ll contact you about this request.</small></form>}
export function FAQ({items}:{items:[string,string][]}){return <div className="faq">{items.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div>}
export function CTA(){return <section className="cta"><div className="shell"><div><span className="kicker light">Start with a conversation</span><h2>Ready to feel more confident about your coverage?</h2><p>Tell us what matters to you. We’ll help you take the next step.</p></div><div><Link href="/#quote" className="button white">Request a Quote</Link><a href={`tel:+1${agency.phone1.replaceAll("-","")}`} className="button ghost">Call {agency.phone1}</a></div></div></section>}
export function Footer(){return <footer><div className="shell foot-grid"><div><Link href="/" className="logo light"><b>S</b><span>SEMECO<small>AGENCY LLC</small></span></Link><p>Clear insurance guidance for Texas families and businesses, from a family-owned agency in Pilot Point.</p></div><div><h3>Insurance</h3>{products.map(p=><Link key={p.slug} href={`/${p.slug}`}>{p.title}</Link>)}</div><div><h3>Agency</h3><Link href="/about">About us</Link><Link href="/contact">Contact</Link><Link href="/privacy-policy">Privacy policy</Link><Link href="/terms">Terms</Link></div><div><h3>Talk with us</h3><a href={`tel:+1${agency.phone1.replaceAll("-","")}`}>{agency.phone1}</a><a href={`tel:+1${agency.phone2.replaceAll("-","")}`}>{agency.phone2}</a><a href={`mailto:${agency.email}`}>{agency.email}</a><p>Pilot Point, Texas</p></div></div><div className="shell foot-bottom"><span>© {new Date().getFullYear()} Semeco Agency LLC.</span><span>Insurance availability and eligibility vary.</span></div></footer>}
