export type Locale="en"|"es";
export const locales:Locale[]=["en","es"];
export const agency={name:"Semeco Agency LLC",phone1:"312-539-5727",phone2:"312-515-4733",email:"semecoagencyllc@gmail.com"};
const en={
 locale:"en-US",language:"English",nav:{home:"Home",insurance:"Insurance",about:"About",contact:"Contact",quote:"Get a Quote",menu:"Menu",close:"Close",switch:"Español"},
 common:{eyebrow:"Family-owned · Pilot Point, Texas",call:"Call Now",learn:"Learn more",request:"Request a Quote",insuranceFor:"Insurance for Texans",overview:"Coverage overview",who:"Who it’s for",benefits:"Potential benefits",questions:"Questions worth asking.",related:"Related insurance products",start:"Start with a conversation",ctaTitle:"Ready to feel more confident about your coverage?",ctaText:"Tell us what matters to you. We’ll help you take the next step.",back:"Home",optional:"Optional",sending:"Submitting does not bind coverage.",serve:"Serving customers across Texas."},
 hero:{title:"Protect What Matters Most.",sub:"Helping Texas families and businesses find insurance coverage with confidence.",trust1:"Helpful, personal guidance",trust2:"No-obligation quote request"},
 quote:{eyebrow:"Free quote request",title:"Let’s find your coverage.",sub:"No pressure. Just a helpful conversation.",name:"Full name",phone:"Phone",email:"Email",zip:"ZIP code",type:"Insurance type",select:"Select one",method:"Preferred contact method",message:"How can we help?",placeholder:"Tell us what you’d like to protect.",submit:"Request my free quote",fine:"By submitting, you agree that Semeco Agency LLC may contact you about this request. Coverage is not bound by this form.",phoneMethod:"Phone",emailMethod:"Email",textMethod:"Text"},
 home:{protect:"What can we help you protect?",options:"Insurance options",chapter:"Coverage for every chapter of life.",chapterText:"Start with what matters today. We’ll help you understand the choices and move forward with clarity.",difference:"The Semeco difference",human:"Insurance should feel clear, personal, and human.",humanText:"We bring a family-agency mindset to every conversation.",aboutEyebrow:"A family-owned agency",aboutTitle:"Coverage conversations built around real life.",aboutText:"Semeco Agency LLC is a family-owned insurance agency in Pilot Point. We listen first, explain choices clearly, and help Texas families and businesses move forward with confidence.",aboutCta:"Learn About Our Agency",stories:"Client experiences",trustTitle:"Trust is earned one conversation at a time.",story1:"Client stories will be shared here as the agency receives permission to publish verified feedback.",story2:"We never publish invented reviews. Future testimonials will reflect genuine client experiences.",coming:"Testimonials coming soon",authentic:"Authenticity first",faqEyebrow:"Common questions",faqTitle:"Helpful answers, before you ask.",faqText:"Insurance can feel complicated. These quick answers are a place to start.",contactEyebrow:"Prefer to talk?",contactTitle:"A real conversation can make all the difference.",contactText:"Call or email our family-owned Pilot Point agency. We’ll help you identify the right next step."},
 why:[{icon:"person",title:"Personalized Service",text:"Guidance shaped around your priorities—not a one-size-fits-all script."},{icon:"bolt",title:"Responsive Quotes",text:"A clear process that keeps you informed about what comes next."},{icon:"pin",title:"Local Texas Agency",text:"Based in Pilot Point and serving communities across Texas."},{icon:"shield",title:"Coverage With Clarity",text:"Straightforward conversations to help you evaluate protection."},{icon:"layers",title:"Multiple Options",text:"Auto, home, life, commercial, and health insurance in one place."}],
 about:{eyebrow:"Our agency",title:"Insurance guidance, grounded in family.",sub:"A local, personal approach for Texas families and businesses.",story:"Our story",heading:"We start by listening.",p1:"Semeco Agency LLC is a family-owned insurance agency based in Pilot Point, Texas. The agency is built around a simple belief: people deserve thoughtful guidance when making decisions about the things and people they value most.",p2:"We take time to understand your situation, explain available paths in plain language, and help you take a confident next step—without inflated claims or pressure-driven conversations.",values:"What guides us",valuesTitle:"Simple values. Meaningful service.",valueItems:["Listen first","Explain clearly","Serve locally","Support the whole picture"]},
 contact:{eyebrow:"We’re here to help",title:"Let’s talk about what matters to you.",sub:"Call, email, or send a message. We’ll respond as promptly as possible.",info:"Business information",location:"Location",hours:"Business hours",hoursList:["Monday–Friday: 9:00 AM–5:00 PM","Saturday: By appointment","Sunday: Closed"],map:"Google Map",mapNote:"Map embed will be added when the public office address is confirmed.",form:"Send a message",formTitle:"How can we help?",message:"Message",send:"Send message"},
 legal:{privacy:"Privacy Policy",terms:"Website Terms",updated:"Last updated: July 16, 2026",privacyBody:["Semeco Agency LLC respects your privacy. This policy explains how information submitted through this website may be collected, used, and protected.","We may collect information you choose to provide, including contact details, ZIP code, insurance interests, and messages. We use it to respond to inquiries and provide customer service. We do not sell personal information.","Submitting a form does not bind coverage. Contact us if you have questions about information you submitted."],termsBody:["This website provides general information and does not create, change, renew, or bind insurance coverage.","Insurance products, eligibility, pricing, exclusions, and availability vary by carrier and circumstance. Coverage is effective only when confirmed through authorized policy documents.","You agree not to misuse the site, attempt unauthorized access, interfere with its operation, or submit unlawful material."]},
 thanks:{title:"Thank you.",text:"Your message has been received. A member of Semeco Agency LLC will follow up.",button:"Return home"},
 faq:[["What information should I have ready for a quote?","Basic contact details, your ZIP code, the insurance type, and current policy information help us begin."],["How quickly can I receive a quote?","Timing depends on the coverage and information required. We respond promptly and explain what is needed next."],["Can you help with multiple types of insurance?","Yes. We can discuss auto, home, life, commercial, and health insurance in one conversation."],["What should I do if I need to make a claim?","Contact the carrier using the claim information on your policy documents. We can help you find the correct path."],["Does requesting a quote obligate me to buy?","No. A quote request is simply a first step toward reviewing available options."],["Do you serve customers outside Pilot Point?","Yes. We help customers across Texas, subject to carrier and product availability."]],
 footer:{desc:"Clear insurance guidance for Texas families and businesses, from a family-owned agency in Pilot Point.",agency:"Agency",talk:"Talk with us",privacy:"Privacy policy",terms:"Terms",notice:"Insurance availability and eligibility vary."}
};
const es={
 locale:"es-US",language:"Español",nav:{home:"Inicio",insurance:"Seguros",about:"Nosotros",contact:"Contacto",quote:"Cotización",menu:"Menú",close:"Cerrar",switch:"English"},
 common:{eyebrow:"Agencia familiar · Pilot Point, Texas",call:"Llamar ahora",learn:"Conocer más",request:"Solicitar cotización",insuranceFor:"Seguros para Texas",overview:"Resumen de cobertura",who:"Para quién es",benefits:"Beneficios potenciales",questions:"Preguntas importantes.",related:"Seguros relacionados",start:"Comience con una conversación",ctaTitle:"¿Listo para sentir más confianza en su cobertura?",ctaText:"Cuéntenos qué es importante para usted. Le ayudaremos con el próximo paso.",back:"Inicio",optional:"Opcional",sending:"Enviar este formulario no activa cobertura.",serve:"Atendemos clientes en todo Texas."},
 hero:{title:"Proteja Lo Que Más Importa.",sub:"Ayudamos a familias y negocios de Texas a encontrar cobertura de seguros con confianza.",trust1:"Orientación personal y útil",trust2:"Solicitud sin compromiso"},
 quote:{eyebrow:"Cotización gratuita",title:"Encontremos su cobertura.",sub:"Sin presión. Solo una conversación útil.",name:"Nombre completo",phone:"Teléfono",email:"Correo electrónico",zip:"Código postal",type:"Tipo de seguro",select:"Seleccione uno",method:"Método de contacto preferido",message:"¿Cómo podemos ayudar?",placeholder:"Cuéntenos qué desea proteger.",submit:"Solicitar mi cotización",fine:"Al enviar, acepta que Semeco Agency LLC pueda contactarle sobre esta solicitud. Este formulario no activa cobertura.",phoneMethod:"Teléfono",emailMethod:"Correo",textMethod:"Texto"},
 home:{protect:"¿Qué podemos ayudarle a proteger?",options:"Opciones de seguro",chapter:"Cobertura para cada etapa de la vida.",chapterText:"Comience con lo que importa hoy. Le ayudamos a entender sus opciones con claridad.",difference:"La diferencia Semeco",human:"El seguro debe ser claro, personal y humano.",humanText:"Aportamos la atención de una agencia familiar a cada conversación.",aboutEyebrow:"Una agencia familiar",aboutTitle:"Conversaciones sobre cobertura basadas en la vida real.",aboutText:"Semeco Agency LLC es una agencia familiar en Pilot Point. Escuchamos primero, explicamos las opciones claramente y ayudamos a familias y negocios de Texas a avanzar con confianza.",aboutCta:"Conozca Nuestra Agencia",stories:"Experiencias de clientes",trustTitle:"La confianza se gana conversación por conversación.",story1:"Compartiremos historias de clientes cuando la agencia reciba permiso para publicar opiniones verificadas.",story2:"Nunca publicamos reseñas inventadas. Los futuros testimonios reflejarán experiencias reales.",coming:"Testimonios próximamente",authentic:"Autenticidad primero",faqEyebrow:"Preguntas frecuentes",faqTitle:"Respuestas útiles, antes de preguntar.",faqText:"Los seguros pueden parecer complicados. Estas respuestas son un buen comienzo.",contactEyebrow:"¿Prefiere hablar?",contactTitle:"Una conversación real puede marcar la diferencia.",contactText:"Llame o escriba a nuestra agencia familiar en Pilot Point. Le ayudaremos a identificar el próximo paso."},
 why:[{icon:"person",title:"Servicio Personalizado",text:"Orientación basada en sus prioridades, no en un guion genérico."},{icon:"bolt",title:"Cotizaciones Ágiles",text:"Un proceso claro que le mantiene informado sobre el próximo paso."},{icon:"pin",title:"Agencia Local de Texas",text:"Con sede en Pilot Point y servicio en comunidades de Texas."},{icon:"shield",title:"Cobertura con Claridad",text:"Conversaciones directas para evaluar su protección."},{icon:"layers",title:"Múltiples Opciones",text:"Seguros de auto, hogar, vida, comercial y salud en un solo lugar."}],
 about:{eyebrow:"Nuestra agencia",title:"Orientación de seguros basada en la familia.",sub:"Un enfoque local y personal para familias y negocios de Texas.",story:"Nuestra historia",heading:"Comenzamos escuchando.",p1:"Semeco Agency LLC es una agencia de seguros familiar en Pilot Point, Texas. La agencia se basa en una idea sencilla: las personas merecen orientación considerada al tomar decisiones sobre lo que más valoran.",p2:"Nos tomamos el tiempo para entender su situación, explicar opciones en lenguaje claro y ayudarle a avanzar con confianza, sin afirmaciones exageradas ni presión.",values:"Lo que nos guía",valuesTitle:"Valores sencillos. Servicio significativo.",valueItems:["Escuchar primero","Explicar claramente","Servir localmente","Apoyar la visión completa"]},
 contact:{eyebrow:"Estamos para ayudar",title:"Hablemos de lo que le importa.",sub:"Llame, escriba o envíe un mensaje. Responderemos lo antes posible.",info:"Información del negocio",location:"Ubicación",hours:"Horario",hoursList:["Lunes–viernes: 9:00 AM–5:00 PM","Sábado: Con cita","Domingo: Cerrado"],map:"Mapa de Google",mapNote:"El mapa se añadirá cuando se confirme la dirección pública de la oficina.",form:"Enviar un mensaje",formTitle:"¿Cómo podemos ayudar?",message:"Mensaje",send:"Enviar mensaje"},
 legal:{privacy:"Política de Privacidad",terms:"Términos del Sitio",updated:"Última actualización: 16 de julio de 2026",privacyBody:["Semeco Agency LLC respeta su privacidad. Esta política explica cómo se puede recopilar, usar y proteger la información enviada mediante este sitio.","Podemos recopilar la información que usted proporciona, incluidos datos de contacto, código postal, intereses de seguros y mensajes. La usamos para responder consultas y brindar servicio. No vendemos información personal.","Enviar un formulario no activa cobertura. Contáctenos si tiene preguntas sobre la información enviada."],termsBody:["Este sitio ofrece información general y no crea, cambia, renueva ni activa cobertura de seguros.","Los productos, elegibilidad, precios, exclusiones y disponibilidad varían según la compañía y las circunstancias. La cobertura solo entra en vigor mediante documentos autorizados.","Usted acepta no usar indebidamente el sitio, intentar acceso no autorizado, interferir con su funcionamiento ni enviar material ilegal."]},
 thanks:{title:"Gracias.",text:"Recibimos su mensaje. Un miembro de Semeco Agency LLC se comunicará con usted.",button:"Volver al inicio"},
 faq:[["¿Qué información necesito para una cotización?","Sus datos de contacto, código postal, tipo de seguro e información de póliza actual nos ayudan a comenzar."],["¿Cuánto tarda una cotización?","Depende de la cobertura y la información necesaria. Respondemos pronto y explicamos el siguiente paso."],["¿Pueden ayudar con varios tipos de seguro?","Sí. Podemos hablar de auto, hogar, vida, comercial y salud en una sola conversación."],["¿Qué hago si necesito presentar un reclamo?","Contacte a la compañía usando la información de reclamos de su póliza. Podemos ayudarle a encontrar el canal correcto."],["¿Solicitar una cotización me obliga a comprar?","No. La solicitud es solamente el primer paso para revisar opciones disponibles."],["¿Atienden fuera de Pilot Point?","Sí. Ayudamos a clientes en Texas, sujeto a disponibilidad de productos y compañías."]],
 footer:{desc:"Orientación clara de seguros para familias y negocios de Texas, de una agencia familiar en Pilot Point.",agency:"Agencia",talk:"Hable con nosotros",privacy:"Privacidad",terms:"Términos",notice:"La disponibilidad y elegibilidad de seguros varían."}
};
export type Dictionary=typeof en;
export function getDictionary(locale:string):Dictionary{return locale==="es"?es:en}

const enProducts=[
 {slug:"auto-insurance",title:"Auto Insurance",short:"Auto",icon:"car",image:"/auto-insurance.jpg",tagline:"Move forward with confidence.",description:"Practical coverage options for your vehicle, passengers, and the road ahead.",overview:"Auto insurance can help with covered vehicle damage, injuries, liability, and unexpected costs after an accident. We help Texas drivers compare practical choices based on how and where they drive.",audience:["Daily commuters","Families with multiple vehicles","New and experienced drivers","Drivers reviewing current coverage"],benefits:["Liability coverage options","Collision and comprehensive options","Uninsured motorist protection","Deductibles aligned to your budget"],faqs:[["What do I need for an auto quote?","Driver information, vehicle details, garaging ZIP code, and current coverage are a helpful starting point."],["Is the lowest premium always best?","Not always. The right fit balances premium, deductible, limits, and the risks you want protected."],["Can I bundle auto and home?","Bundling may be available depending on the carrier and products selected."]]},
 {slug:"home-insurance",title:"Home Insurance",short:"Home",icon:"home",image:"/semeco-hero.jpg",tagline:"Protect the place that holds your life.",description:"Coverage options for your home, belongings, liability, and more.",overview:"Home insurance is designed to help protect your residence, belongings, and finances from certain covered losses. We take time to understand the property and the protection that matters to you.",audience:["Homeowners","First-time homebuyers","Rental property owners","Families reviewing coverage"],benefits:["Dwelling protection options","Personal property coverage","Personal liability protection","Additional living expense coverage"],faqs:[["How much home coverage do I need?","Coverage is commonly based on estimated rebuilding costs rather than market value."],["Does home insurance cover flooding?","Standard home policies typically exclude flood damage. Separate flood coverage may be worth discussing."],["Should I create a home inventory?","Yes. A current photo or video inventory can help document belongings after a covered loss."]]},
 {slug:"life-insurance",title:"Life Insurance",short:"Life",icon:"heart",image:"/life-insurance.jpg",tagline:"Help secure their tomorrow.",description:"Flexible options designed to support the people who count on you.",overview:"Life insurance can provide financial support to the people you choose after your death. We explain common policy types in plain language so you can make an informed decision.",audience:["Parents and caregivers","Homeowners with a mortgage","Business owners","People with shared obligations"],benefits:["Term and permanent options","Beneficiary flexibility","Coverage aligned to your goals","A pressure-free review"],faqs:[["When should I consider life insurance?","Major life changes are natural times to review coverage."],["What is term life insurance?","Term life provides coverage for a defined period, subject to the policy terms."],["How much coverage should I consider?","Income, debt, family needs, and savings all matter."]]},
 {slug:"commercial-insurance",title:"Commercial Insurance",short:"Commercial",icon:"briefcase",image:"/commercial-insurance.jpg",tagline:"Built around the business you’re building.",description:"Coverage options for Texas businesses, property, liability, vehicles, and people.",overview:"Commercial insurance helps businesses prepare for property damage, liability claims, interruptions, and other covered risks. We start with how your business actually operates.",audience:["Local service businesses","Retail and office operations","Contractors and trades","Growing Texas companies"],benefits:["General liability options","Commercial property protection","Business auto options","Coverage shaped to operations"],faqs:[["What commercial coverage might I need?","Needs vary by operations, property, vehicles, contracts, employees, and industry."],["What is general liability insurance?","It may help with certain bodily injury, property damage, and related legal claims."],["Can coverage change as my business grows?","Yes. Review coverage as revenue, services, staff, equipment, or locations change."]]},
 {slug:"health-insurance",title:"Health Insurance",short:"Health",icon:"health",image:"/health-insurance.jpg",tagline:"Clarity for an important decision.",description:"Navigate health coverage choices for yourself, your family, or your team.",overview:"Health insurance options can differ in network, cost sharing, benefits, and eligibility. We help you organize priorities and understand available choices.",audience:["Individuals and families","Self-employed professionals","People in a coverage transition","Small business teams"],benefits:["Plain-language guidance","Plan comparison support","Network and cost considerations","Help understanding next steps"],faqs:[["What should I compare beyond premium?","Consider deductibles, copays, coinsurance, out-of-pocket maximums, networks, and prescriptions."],["Can I enroll at any time?","Timing depends on the plan, annual enrollment periods, and special enrollment eligibility."],["How do I check my doctor’s network?","Carrier directories are a starting point; direct confirmation is recommended."]]},
] as const;
export type Product=typeof enProducts[number];
const esCopy=[
 ["Seguro de Auto","Auto","Avance con confianza.","Opciones prácticas para su vehículo, pasajeros y el camino.","El seguro de auto puede ayudar con daños cubiertos, lesiones, responsabilidad y costos inesperados. Le ayudamos a comparar opciones según cómo y dónde conduce.",["Personas que viajan al trabajo","Familias con varios vehículos","Conductores nuevos y experimentados","Quienes revisan su cobertura"],["Opciones de responsabilidad","Colisión y cobertura amplia","Protección contra conductores sin seguro","Deducibles según su presupuesto"]],
 ["Seguro de Hogar","Hogar","Proteja el lugar donde vive su historia.","Opciones para su hogar, pertenencias, responsabilidad y más.","El seguro de hogar ayuda a proteger su vivienda, pertenencias y finanzas ante ciertas pérdidas cubiertas. Conocemos la propiedad y la protección que le importa.",["Propietarios de vivienda","Compradores primerizos","Dueños de propiedades de alquiler","Familias que revisan cobertura"],["Protección de vivienda","Cobertura de bienes personales","Responsabilidad personal","Gastos adicionales de vivienda"]],
 ["Seguro de Vida","Vida","Ayude a proteger su futuro.","Opciones flexibles para apoyar a quienes dependen de usted.","El seguro de vida puede brindar apoyo financiero a las personas que usted elija. Explicamos los tipos de póliza en lenguaje sencillo.",["Padres y cuidadores","Propietarios con hipoteca","Dueños de negocios","Personas con obligaciones compartidas"],["Opciones temporales y permanentes","Flexibilidad de beneficiarios","Cobertura según sus metas","Revisión sin presión"]],
 ["Seguro Comercial","Comercial","Creado para el negocio que está construyendo.","Opciones para negocios, propiedad, responsabilidad, vehículos y personal.","El seguro comercial ayuda a los negocios a prepararse para daños, reclamos, interrupciones y otros riesgos cubiertos. Comenzamos con la forma en que opera.",["Negocios locales de servicios","Tiendas y oficinas","Contratistas y oficios","Empresas de Texas en crecimiento"],["Responsabilidad general","Protección de propiedad comercial","Opciones para autos comerciales","Cobertura según sus operaciones"]],
 ["Seguro de Salud","Salud","Claridad para una decisión importante.","Navegue opciones de salud para usted, su familia o su equipo.","Las opciones de salud varían en red, costos, beneficios y elegibilidad. Le ayudamos a organizar prioridades y entender las opciones.",["Personas y familias","Profesionales independientes","Personas en transición de cobertura","Equipos de pequeñas empresas"],["Orientación en lenguaje claro","Comparación de planes","Consideraciones de red y costos","Ayuda con los próximos pasos"]]
] as const;
export function getProducts(locale:string){if(locale!=="es")return enProducts;return enProducts.map((p,i)=>({...p,title:esCopy[i][0],short:esCopy[i][1],tagline:esCopy[i][2],description:esCopy[i][3],overview:esCopy[i][4],audience:esCopy[i][5],benefits:esCopy[i][6],faqs:[["¿Qué información necesito para comenzar?","Sus datos básicos y cualquier cobertura actual son un buen comienzo."],["¿Cómo comparo opciones?","Revise precio, límites, deducibles, beneficios, exclusiones y sus prioridades."],["¿Puedo solicitar ayuda sin compromiso?","Sí. Una solicitud de cotización no le obliga a comprar."]] as [string,string][]}))}
