import type {Metadata} from "next";
import {Manrope,Newsreader} from "next/font/google";
import {Header,Footer} from "./components";
import {agency} from "./data";
import "./globals.css";
const sans=Manrope({subsets:["latin"],variable:"--sans",display:"swap"});
const serif=Newsreader({subsets:["latin"],variable:"--serif",display:"swap"});
export const metadata:Metadata={metadataBase:new URL("https://semecoagency.com"),title:{default:"Semeco Agency LLC | Insurance Agency in Pilot Point, TX",template:"%s | Semeco Agency LLC"},description:"A family-owned insurance agency helping Texas families and businesses explore auto, home, life, commercial, and health insurance.",keywords:["Insurance Agency Pilot Point","Auto Insurance Pilot Point","Home Insurance Pilot Point","Commercial Insurance Texas","Life Insurance Texas","Health Insurance Pilot Point"],openGraph:{type:"website",locale:"en_US",siteName:"Semeco Agency LLC",title:"Semeco Agency LLC | Insurance With Confidence",description:"Helping Texas families and businesses find insurance coverage with confidence.",images:[{url:"/semeco-hero.png",width:1680,height:945,alt:"A Texas family outside their home"}]},twitter:{card:"summary_large_image",title:"Semeco Agency LLC",description:"Insurance guidance for Texas families and businesses.",images:["/semeco-hero.png"]},robots:{index:true,follow:true},icons:{icon:"/favicon.svg"}};
export default function Layout({children}:{children:React.ReactNode}){const schema={"@context":"https://schema.org","@type":"InsuranceAgency",name:agency.name,url:"https://semecoagency.com",telephone:[agency.phone1,agency.phone2],email:agency.email,address:{"@type":"PostalAddress",addressLocality:"Pilot Point",addressRegion:"TX",addressCountry:"US"},areaServed:{"@type":"State",name:"Texas"},knowsAbout:["Auto Insurance","Home Insurance","Life Insurance","Commercial Insurance","Health Insurance"]};return <html lang="en" className={`${sans.variable} ${serif.variable}`}><body><a className="skip" href="#main">Skip to content</a><Header/><main id="main">{children}</main><Footer/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></body></html>}
