import Link from "next/link";
import {CTA,FAQ,Icon,QuoteForm} from "./components";
import {agency,homeFaqs,products} from "./data";
const why=[{icon:"person",title:"Personalized Service",text:"Real guidance shaped around your priorities—not a one-size-fits-all script."},{icon:"bolt",title:"Fast Quotes",text:"A responsive process that keeps you informed about what comes next."},{icon:"pin",title:"Local Texas Agency",text:"Family-owned and based right here in Pilot Point, serving communities across Texas."},{icon:"check",title:"Trusted Coverage",text:"Clear conversations that help you evaluate protection with confidence."},{icon:"layers",title:"Multiple Options",text:"Auto, home, life, commercial, and health insurance in one helpful place."}];
export default function Home(){return <>
 <section className="hero" id="quote"><div className="hero-bg"/><div className="shell hero-grid"><div className="hero-copy"><span className="kicker light">Family-owned · Pilot Point, Texas</span><h1>Protect What<br/><em>Matters Most.</em></h1><p>Helping Texas families and businesses find insurance coverage with confidence.</p><div className="hero-actions"><Link href="#quote-form" className="button white">Get a Free Quote</Link><a href={`tel:+1${agency.phone1.replaceAll("-","")}`} className="button ghost">Call Now</a></div><div className="hero-trust"><span><Icon name="check"/> Helpful, personal guidance</span><span><Icon name="check"/> No-obligation quote request</span></div></div><div id="quote-form"><QuoteForm/></div></div></section>
 <section className="quick"><div className="shell"><p>What can we help you protect?</p>{products.map(p=><Link key={p.slug} href={`/${p.slug}`}><Icon name={p.icon}/><span>{p.short}<small>Insurance</small></span></Link>)}</div></section>
 <section className="section shell"><div className="section-head"><div><span className="kicker">Insurance options</span><h2>Coverage for every<br/><em>chapter of life.</em></h2></div><p>Start with what matters today. We’ll help you understand the choices and move forward with clarity.</p></div><div className="product-grid">{products.map((p,i)=><Link href={`/${p.slug}`} className={`product-card p${i}`} key={p.slug}><span className="icon"><Icon name={p.icon}/></span><small>0{i+1}</small><h3>{p.title}</h3><p>{p.description}</p><b>Learn more <span>→</span></b></Link>)}</div></section>
 <section className="why"><div className="shell"><div className="center-head"><span className="kicker light">The Semeco difference</span><h2>Insurance should feel clear,<br/><em>personal, and human.</em></h2><p>We bring a family-agency mindset to every conversation.</p></div><div className="why-grid">{why.map(x=><article key={x.title}><span><Icon name={x.icon}/></span><h3>{x.title}</h3><p>{x.text}</p></article>)}</div></div></section>
 <section className="about-preview shell"><div className="about-photo"><div className="monogram">S</div><span>Proudly serving Texas</span></div><div><span className="kicker">A family-owned agency</span><h2>Coverage conversations built around <em>real life.</em></h2><p>Semeco Agency LLC is a family-owned insurance agency in Pilot Point, Texas. We believe insurance starts with listening—understanding your family, business, priorities, and questions before exploring coverage.</p><p>Our goal is simple: make the process more approachable and help you feel informed at every step.</p><Link href="/about" className="button primary">Learn About Our Agency <span>→</span></Link></div></section>
 <section className="testimonials"><div className="shell"><div><span className="kicker">Client experiences</span><h2>Trust is earned<br/>one conversation at a time.</h2></div><article><div className="quote-mark">“</div><p>Client stories will be shared here as the agency receives permission to publish verified feedback.</p><span>Testimonials coming soon</span></article><article><div className="quote-mark">“</div><p>We never publish invented reviews. Future testimonials will reflect genuine client experiences.</p><span>Authenticity first</span></article></div></section>
 <section className="section faq-section shell"><div><span className="kicker">Common questions</span><h2>Helpful answers,<br/><em>before you ask.</em></h2><p>Insurance can feel complicated. These quick answers are a place to start.</p><Link href="/contact" className="text-link">Still have a question? Contact us →</Link></div><FAQ items={homeFaqs}/></section>
 <CTA/>
 </>}
