import type {Metadata} from "next";
import {notFound} from "next/navigation";
import Link from "next/link";
import {CTA,FAQ} from "../components";
import {agency,products} from "../data";
export function generateStaticParams(){return products.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const p=products.find(x=>x.slug===slug);if(!p)return{};return{title:`${p.title} in Pilot Point, Texas`,description:`Explore ${p.title.toLowerCase()} options with Semeco Agency LLC, a family-owned insurance agency serving Pilot Point and communities across Texas.`,alternates:{canonical:`/${p.slug}`},openGraph:{title:`${p.title} | Semeco Agency LLC`,description:p.description,url:`/${p.slug}`}}}
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const p=products.find(x=>x.slug===slug);if(!p)notFound();const related=products.filter(x=>x.slug!==p.slug).slice(0,3);return <>
 <section className="inner-hero"><div className="shell"><div className="breadcrumbs"><Link href="/">Home</Link> / {p.title}</div><span className="kicker light">Insurance for Texans</span><h1>{p.tagline}</h1><p>{p.description} Clear answers start with a personal conversation.</p><div className="hero-actions"><Link href="/#quote" className="button white">Request a Quote</Link><a href={`tel:+1${agency.phone1.replaceAll("-","")}`} className="button ghost">Call Now</a></div></div></section>
 <section className="content-section shell"><div className="content-grid"><div><span className="kicker">Coverage overview</span><h2>Understand your options.<br/><em>Choose with confidence.</em></h2><p>{p.overview}</p><p>Policy features, eligibility, exclusions, and availability vary. We’ll help you identify useful questions and review the information available for your situation.</p></div><div className="list-card"><h3>Who it’s for</h3><ul>{p.audience.map(x=><li key={x}>{x}</li>)}</ul></div></div></section>
 <section className="benefits-section"><div className="shell"><div className="section-head"><div><span className="kicker">Potential benefits</span><h2>Protection designed around<br/><em>the way you live.</em></h2></div><p>Every policy is different. These are common areas we can help you explore.</p></div><div className="benefits">{p.benefits.map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3></article>)}</div></div></section>
 <section className="section shell faq-section"><div><span className="kicker">{p.short} insurance FAQ</span><h2>Questions worth<br/><em>asking.</em></h2><p>We welcome your questions and explain the next steps in plain language.</p><a href={`tel:+1${agency.phone1.replaceAll("-","")}`} className="text-link">Call {agency.phone1} →</a></div><FAQ items={p.faqs}/></section>
 <section className="section shell"><div className="section-head"><div><span className="kicker">Explore more</span><h2>Related insurance products</h2></div><p>Your coverage needs often connect. Explore other ways we can help.</p></div><div className="related">{related.map(x=><Link key={x.slug} href={`/${x.slug}`}><small>{x.short} insurance</small><h3>{x.title}</h3><span>Learn more →</span></Link>)}</div></section><CTA/>
 </>}
