import type {Metadata} from "next";
import Image from "next/image";
import Link from "next/link";
import {notFound} from "next/navigation";
import {agency,getDictionary,getProducts,Locale,locales} from "../i18n";
import {ContactStrip,CTA,FAQ,Icon,QuoteForm} from "../ui";
export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const{locale}=await params;const es=locale==="es";return{title:es?"Seguros para Familias y Negocios de Texas":"Insurance for Texas Families and Businesses",description:es?"Solicite una cotización de auto, hogar, vida, comercial o salud con Semeco Agency LLC en Pilot Point.":"Request an auto, home, life, commercial, or health insurance quote with Semeco Agency LLC in Pilot Point.",alternates:{canonical:`/${locale}`,languages:{"en-US":"/en","es-US":"/es","x-default":"/en"}}}}
export default async function Home({params}:{params:Promise<{locale:string}>}){const{locale}=await params;if(!locales.includes(locale as Locale))notFound();const l=locale as Locale,d=getDictionary(l),products=getProducts(l),stats=l==="es"?[["5","Tipos de cobertura"],["2","Idiomas disponibles"],["Texas","Área de servicio"]]:[["5","Coverage categories"],["2","Languages available"],["Texas","Service area"]],steps=l==="es"?[["01","Cuéntenos qué necesita","Comparta sus prioridades por teléfono o mediante el formulario."],["02","Revise opciones claras","Le ayudamos a entender la información disponible sin presión."],["03","Avance con confianza","Elija el próximo paso que tenga sentido para usted."]]:[["01","Tell us what you need","Share your priorities by phone or through the quote form."],["02","Review clear options","We help you understand available information without pressure."],["03","Move forward confidently","Choose the next step that makes sense for you."]];return <>
 <section className="home-hero" id="quote"><Image src="/semeco-hero.png" alt={l==="es"?"Familia de Texas frente a su casa y vehículo":"Texas family outside their home and vehicle"} fill priority sizes="100vw"/><div className="home-overlay"/><div className="shell home-grid"><div className="home-copy reveal"><span className="kicker light">{d.common.eyebrow}</span><h1>{d.hero.title}</h1><p>{d.hero.sub}</p><div className="hero-actions"><Link href="#quote-card" className="button white">{d.nav.quote}</Link><a href={`tel:+1${agency.phone1.replaceAll("-","")}`} className="button ghost">{d.common.call}</a></div><div className="trust-badges"><span><Icon name="shield"/>{d.hero.trust1}</span><span><Icon name="check"/>{d.hero.trust2}</span></div></div><div id="quote-card" className="quote-float reveal delay"><QuoteForm locale={l}/></div></div></section>
 <section className="quick"><div className="shell"><p>{d.home.protect}</p>{products.map(p=><Link key={p.slug} href={`/${l}/${p.slug}`}><Icon name={p.icon}/><span>{p.short}</span></Link>)}</div></section>
 <section className="stats"><div className="shell">{stats.map(([value,label])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></section>
 <section className="section shell"><div className="section-head reveal"><div><span className="kicker">{d.home.options}</span><h2>{d.home.chapter}</h2></div><p>{d.home.chapterText}</p></div><div className="visual-grid">{products.map((p,i)=><Link href={`/${l}/${p.slug}`} className={`visual-card card-${i}`} key={p.slug}><Image src={p.image} alt={p.description} fill sizes="(max-width: 700px) 100vw, 40vw"/><div className="card-shade"/><span className="card-icon"><Icon name={p.icon}/></span><div><small>0{i+1}</small><h3>{p.title}</h3><p>{p.description}</p><b>{d.common.learn} →</b></div></Link>)}</div></section>
 <section className="why"><div className="shell"><div className="center-head reveal"><span className="kicker light">{d.home.difference}</span><h2>{d.home.human}</h2><p>{d.home.humanText}</p></div><div className="why-grid">{d.why.map(x=><article key={x.title}><span><Icon name={x.icon}/></span><h3>{x.title}</h3><p>{x.text}</p></article>)}</div></div></section>
 <section className="process-section section"><div className="shell"><div className="center-head"><span className="kicker">{l==="es"?"Cómo funciona":"How it works"}</span><h2>{l==="es"?"Un proceso sencillo y personal.":"A simple, personal process."}</h2><p>{l==="es"?"Tres pasos claros para comenzar.":"Three clear steps to get started."}</p></div><div className="process-grid">{steps.map(([number,title,text])=><article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
 <section className="about-preview shell"><div className="image-panel reveal"><Image src="/about-advisor.png" alt={l==="es"?"Asesora de seguros reunida con clientes":"Insurance advisor meeting with clients"} fill sizes="(max-width: 900px) 100vw, 50vw"/></div><div className="reveal"><span className="kicker">{d.home.aboutEyebrow}</span><h2>{d.home.aboutTitle}</h2><p>{d.home.aboutText}</p><Link href={`/${l}/about`} className="button primary">{d.home.aboutCta}<span>→</span></Link></div></section>
 <section className="service-area"><div className="shell"><div><span className="kicker light">{l==="es"?"Servicio local":"Local service area"}</span><h2>{l==="es"?"Con sede en Pilot Point. Sirviendo a Texas.":"Based in Pilot Point. Serving Texas."}</h2><p>{l==="es"?"Nuestra agencia familiar ayuda a familias y negocios en comunidades del norte de Texas y en todo el estado, sujeto a disponibilidad.":"Our family-owned agency helps families and businesses in North Texas communities and across the state, subject to availability."}</p><Link className="button white" href={`/${l}/contact`}>{d.nav.contact}</Link></div><div className="area-map" role="img" aria-label={l==="es"?"Área de servicio en el norte de Texas":"North Texas service area"}><div className="map-ring ring-one"/><div className="map-ring ring-two"/><span className="map-pin"><Icon name="pin"/></span><strong>Pilot Point</strong><small>North Texas</small><div className="city city-a">Denton</div><div className="city city-b">Frisco</div><div className="city city-c">Gainesville</div></div></div></section>
 <section className="testimonials"><div className="shell"><div><span className="kicker">{d.home.stories}</span><h2>{d.home.trustTitle}</h2></div><article><div className="quote-mark">“</div><p>{d.home.story1}</p><span>{d.home.coming}</span></article><article><div className="quote-mark">“</div><p>{d.home.story2}</p><span>{d.home.authentic}</span></article></div></section>
 <section className="section faq-section shell"><div><span className="kicker">{d.home.faqEyebrow}</span><h2>{d.home.faqTitle}</h2><p>{d.home.faqText}</p></div><FAQ items={d.faq}/></section><ContactStrip locale={l}/><CTA locale={l}/>
 </>}
